# -*- coding: utf-8 -*-
"""UTS_NO_1A

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TIZ0lOvRwtP0kTmi7r0Rbf7cfi94-X61
"""

import numpy as np

inputs = [2.0, 0.4, 2.3, 3.1, 4.2, 6.5, 7.8, 1.2, 0.1, 0.2]
weights = [0.3, 9.0, 0.5, 5.2, 0.3, 0.2, 5.3, 9.0, 4.0, 5.2]

bias = 0.3

outputs = np.dot(weights, inputs) + bias
print(outputs)