# -*- coding: utf-8 -*-
"""UTS_NO_1B

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ManGkxxJYPtaxOJ2hGMg4FBaWCrwkLrB
"""

import numpy as np

inputs = [4.0, 0.4, 2.5, 1.1, 4.2, 6.5, 7.8, 1.2, 0.1, 0.2]
weights = [
    [15.3, 9.4, 0.6, 12.2, 10.3, 0.2, 5.3, 9.0, 4.0, 5.2],
    [5.3, 19.4, 0.1, 2.2, 1.3, 10.2, 15.4, 2.0, 3.0, 3.2],
    [6.8, 9.3, 1.2, 12.7, 0.3, 0.9, 6.6, 9.1, 14.0, 15.2],
    [9.1, 21.4, 20.2, 32.2, 0.7, 7.2, 5.3, 8.0, 5.0, 5.2],
    [11.8, 19.3, 11.2, 2.2, 0.4, 6.9, 7.2, 9.1, 4.1, 5.5],
]
    
biases = [2.5, 5.3, 0.5, 2.3, 3.5]

outputs = np.dot(weights, inputs) + biases
print(outputs)